import '../styles/globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import type { AppProps } from 'next/app';
import { ThemeProvider as MuiThemeProvider } from '@mui/material/styles';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { WagmiProvider } from 'wagmi';
import { RainbowKitProvider } from '@rainbow-me/rainbowkit';
import { config } from '../utils/wagmi';
import theme from '../utils/theme';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head';
import Layout from '../components/Layout';
import { ThemeProvider } from '../contexts/ThemeContext';

const client = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Meta Node Stake</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.svg" rel="icon" type="image/svg+xml" />
      </Head>
      <ThemeProvider>
        <MuiThemeProvider theme={theme}>
          <WagmiProvider config={config}>
            <QueryClientProvider client={client}>
              <RainbowKitProvider locale='en-US'>
                <ToastContainer
                  position="top-right"
                  autoClose={3000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick
                  rtl={false}
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="light"
                  toastClassName="custom-toast"
                  className="custom-toast-body"
                />
                <Layout><Component {...pageProps} /></Layout>
              </RainbowKitProvider>
            </QueryClientProvider>
          </WagmiProvider>
        </MuiThemeProvider>
      </ThemeProvider>
    </>

  );
}

export default MyApp;
